name Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:  [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up api
      uses: actions/setup-api@4
      with:
        go-version: 1.21

    - name: Install dependecies
      run: go mod tidy

    - name: Run tests
      run: go test ./...

    - name: Lint
      run: go vet ./...
